'$schema': 'https://json-schema.org/draft/2020-12/schema'
title: additionalProperty PropertyValue
description: 'PropertyValue values required to define a soft-typed property with a value. '
type: object
properties:
  '@type':
    type: array
    items:
      type: string
    contains:
      const: 'schema:PropertyValue'
    minItems: 1
  'schema:propertyID':
    type: array
    items:
      anyOf:
      - type: string
      - type: object
        required:
        - '@id'
        additionalProperties: false
        properties:
          '@id':
            type: string
      - '$ref': >-
          ../../../../../../../metadataBuildingBlocks/_sources/schemaorgProperties/definedTerm/schema.yaml
    minItems: 1
    description: >-
      identifier or name for the property concept quantified by the values in this variable
      slot. Multiple values can specify the property at different levels of granularity.
  'schema:name':
    type: string
  'schema:value':
    '$ref': '#/$defs/AdditionalPropertyValueChoice'
  'schema:unitCode':
    anyOf:
    - type: string
    - '$ref': >-
        ../../../../../../../metadataBuildingBlocks/_sources/schemaorgProperties/definedTerm/schema.yaml
  'schema:unitText':
    type: string
required:
- 'schema:name'
- 'schema:value'
'$defs':
  AdditionalPropertyValueChoice:
    anyOf:
    - type: string
    - type: number
    - type: boolean
    - '$ref': '#/$defs/AdditionalPropertyValueObject'
  AdditionalPropertyValueObject:
    type: object
